Vagrant.configure("2") do |config|  
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "qliksense-minikube"
  config.vm.network "private_network", ip: "192.168.56.234"
  config.vm.provider "virtualbox" do |v|
    v.name = "qliksense-minikube"
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--memory", 6144]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", 64]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--chipset", "ich9"]
  end  
  config.vm.synced_folder "./files", "/vagrant/files"
  config.vm.provision "bootstrap", type: "shell", path: "./sh/1_bootstrap.sh"
  config.vm.provision "docker", type: "shell", path: "./sh/2_docker.sh"
  config.vm.provision "minikube", type: "shell", path: "./sh/3_minikube.sh"
  config.vm.provision "nfs", type: "shell", path: "./sh/4_nfs.sh"
  config.vm.provision "mongodb", type: "shell", path: "./sh/5_mongo.sh"
end
