apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellochristof-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellochristofapp  
  template:
    metadata:
      name: hellochristof-rcpod
      labels:
        app: hellochristofapp
    spec:
      containers:
      - name: hellochristof-container
        image: qristof/hello-christof
        ports: 
        - containerPort: 8074
