apiVersion: v1
kind: Pod
metadata:
  name: hellochristofpod
  labels:
    app: hellochristofapp
spec:
  containers:
  - name: hellochristof-container
    image: qristof/hello-christof
    ports: 
    - containerPort: 8074
      name: hellochristof-port
      # a name for the port is optional but good for a service to dynamically look it up by name

# to create this pod type
# kubectl create -f pod1.yaml
# To expose the port you need to create a service
# kubectl create -f service4pod1.yaml
