apiVersion: v1
kind: Pod
metadata:
  name: hellochris-pod1
  labels:
    app: hellochris-app1
spec:
  containers:
  - name: hellochris-container
    image: qristof/hello-christof
    ports: 
    - containerPort: 8074

# to create this pod type
# kubectl create -f pod1.yaml
# To expose the port you need to create a service
# kubectl create -f service4pod1.yaml
