# like pod1.yaml but this time using a name for the port, which can be used in service

apiVersion: v1
kind: Pod
metadata:
  name: hellochristofpod
  labels:
    app: hellochristofapp
spec:
  containers:
  - name: hellochristof-container
    image: qristof/hello-christof
    ports: 
    - containerPort: 8074
      name: hellochris-port
      # the port name (15 chars max) will be used by the service yaml
      
# to create this pod type
# kubectl create -f pod2.yaml
# To expose the port you need to create a service
# kubectl create -f service4pod2.yaml
