apiVersion: v1
kind: ReplicationController
metadata:
  name: hellochristof-rc
spec:
  replicas: 3
  #selector:
  #  app: hellochristofapp
  template:
    metadata:
      name: hellochristofpod
      labels:
        app: hellochristofapp
    spec:
      containers:
      - name: hellochristof-container
        image: qristof/hello-christof
        ports: 
        - containerPort: 8074
