apiVersion: v1
kind: Service
metadata:
  name: hellochristof-svc2
spec:
  type: NodePort
  selector:
    app: hellochristofapp 
    # same key-value pair as in metadata.labels section of Pod 
  ports: 
  - port: 12345   
    # non-exposed port number, can be anything  
    nodePort: 31003
    targetPort: hellochris-port  
    # matching the port name given in the pod2.yaml file
    protocol: TCP
