apiVersion: v1
kind: Service
metadata:
  name: hellochristof-svc
spec:
  type: NodePort
  selector:
    app: hellochristofapp 
    # same key-value pair as in metadata.labels section of Pod 
  ports: 
  - port: 8074
    nodePort: 31002
    protocol: TCP
