apiVersion: v1
kind: Pod
metadata:
  name: hellochristofpod
  labels:
    app: hellochristofapp
spec:
  containers:
  - name: hellochristof-container
    image: qristof/hello-christof
    ports: 
    - containerPort: 8074

# to expose this port you need this command to start a service:
# kubectl expose pod hellochristofpod --type NodePort --name hellochristofservice
