apiVersion: v1
kind: Pod
metadata:
  name: hellochristofpod
  labels:
    app: hellochristofapp
spec:
  containers:
  - name: k8s-hello-christof
    image: qristof/hello-christof
    ports: 
    - containerPort: 8074
