# Christof Schwarz, 08-sep-2019

apiVersion: v1
kind: Service
metadata:
  name: qlikcustom-getjwt-np
spec:
  type: NodePort
  selector:
    app: impersonateqseok
    # same key-value pair as in metadata.labels section of Pod 
  ports: 
  - port: 31974    # matching the port number of the app (pod) 
    nodePort: 31975  # desired pod number from external
    protocol: TCP

